### ISSUE TITLE
this is awesome!

### ISSUE THREAD

**Issue by AlkanV** [nicolasLepy/TheManager#3]
hello, 

this project is just amazing. big kudos for what you have done so far. 
i have couple of questions regarding with the simulation algorithm: 

1. is it possible to create a fantasy player with several parameters like FIFA game does? for example: 
Cristiano Ronaldo 
Overall: 91,
Finishing: 95,
Penalties: 88,
Crossing: 87,
Passing: 80,
Jumping: 95,
Heading: 90

2. is it possible to create fantasy team (which has fantasy player squad) and simulate that team with different fantasy or real teams?

thank you for your answer,

best wishes,

alkan.

**Comment by nicolasLepy** [comment]
Hello,
Thank you for your comment !

To answer your questions,

1. For now the simulation algorithm is far too little developed to take into account all the attributes of each players, only an overall attribute is used, although in the future the objective is to have a finer simulation of the games, but for now the objective is to implement the remaining basic functionalities (like transfers...)

2. All database from players to tournaments rules is designed on an xml file, so everything can be edited. But currently this project is under development and can't be released as it because some basic features are not implemented yet !

Best wishes
Nicolas
